version: '3.9'
services:
  # api:
  #   build: ./api/
  #   volumes:
  #     - ./api:/usr/src/app
  #   ports:
  #     - 3000:3000
  #     - 9229:9229
  #   depends_on:
  #     - cache
  #   environment:
  #     NODE_ENV: development
  #     PORT: 3000
  #     REDIS_HOST: cache
  #     REDIS_PORT: 6379

  # cache:
  #   image: redis:6.2-alpine
  #   restart: always
  #   command: redis-server
  #   ports:
  #     - 6379:6379

  client:
    build: ./client/
    volumes:
      - ./client:/app
    ports:
      - 3030:3030
    environment:
      - NODE_ENV=development
      - PORT=3030
